### ISSUE TITLE
Parse Error

### ISSUE THREAD

**Issue by Majidkadi** [ascsoftw/tall_crud_example#7]
Hello,

I've just installed tall_crud_example and when clicking on "Eager Load" menu, I get this error: (see attachement)
![parseerror](https://user-images.githubusercontent.com/31285669/136464699-b8be2476-22f8-4ef8-ac6e-ccd62c730bd5.JPG)

I get the same error when clicking on "Add Edit Form" menu.
It looks like the problem is the brand variable.

**Comment by Majidkadi** [comment]
I found the problem.
In the files "livewire.products.blade.php" and "livewire.eager-load.blade.php" there is a "?" extra character in: 
{{ $result->brand?->name}}
<x:tall-crud-generator::table-column>{{ $result->brand?->name}}</x:tall-crud-generator::table-column>

All what I have to do is delete that extra character.

<x:tall-crud-generator::table-column>{{ $result->brand->name}}</x:tall-crud-generator::table-column>

**Comment by ascsoftw** [comment]
Hi,

Its not an error. Thats the Null Safe Operator introduced in PHP 8.

**Comment by Majidkadi** [comment]
Duplicate of #

**Comment by Majidkadi** [comment]
So how should I fix that?

It's okay I have read the doc.

I will update my PHP version 

Thanks
